version: '3'

services:
  django:
    container_name: django_backend
    build: ./backend
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  # TODO: Create frontend:)
  #react:
  #  container_name: react_frontend
  #  build: ./frontend
  #  volumes:
  #    - '.:/app'
  #    - '/app/node_modules'
  #  ports:
  #    - 3001:3000
  #  environment:
  #    - CHOKIDAR_USEPOLLING=true
