version: '3'

services:
  django:
    container_name: django_backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: unless-stopped

  react:
    container_name: react_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    restart: unless-stopped
