# Generated by Django 3.0.7 on 2021-01-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Count',
                'verbose_name_plural': 'Counts',
                'db_table': 'counts',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('total', models.PositiveSmallIntegerField()),
                ('deepest', models.CharField(max_length=300, verbose_name='Deepest')),
                ('path', models.CharField(max_length=300, verbose_name='Deepest path with most of most popular tags')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('counts', models.ManyToManyField(to='tags.Count')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
                'db_table': 'urls',
            },
        ),
        migrations.AddField(
            model_name='count',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tags.Tag'),
        ),
    ]
